services:
  photon:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/fvoges/docker-photon
    volumes:
      - ./data:/photon/photon_data
    ports:
      - 2322:2322

volumes:
  data:
    driver: local
